version: '2'

services:

  mySQL:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_ROOT_PASSWORD=pass

  NodeJS:
    build: .
    image: node-app:1.0
    ports:
      - '9999:9999'

  PostgreSQL:

    image: postgres:12-alpine
    ports:
      - '9999-9999'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
