version: '2'

services:

  node-app:
    build: .
    image: node
    ports:
      - '9999:9999'

  PostgreSQL:

    image: postgres:12-alpine
    ports:
      - '9999-9999'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    container_name: PostgreSQL
